# Module 3: Data Structures Assignments
## Lesson 3.4: Dictionaries
### Assignment 1: Creating and Accessing Dictionaries

Create a dictionary with the first 10 positive integers as keys and their squares as values. Print the dictionary.

### Assignment 2: Accessing Dictionary Elements

Print the value of the key 5 and the keys of the dictionary created in Assignment 1.

### Assignment 3: Dictionary Methods

Add a new key-value pair (11, 121) to the dictionary created in Assignment 1 and then remove the key-value pair with key 1. Print the modified dictionary.

### Assignment 4: Iterating Over Dictionaries

Iterate over the dictionary created in Assignment 1 and print each key-value pair.

### Assignment 5: Dictionary Comprehensions

Create a new dictionary containing the cubes of the first 10 positive integers using a dictionary comprehension. Print the new dictionary.

### Assignment 6: Merging Dictionaries

Create two dictionaries: one with keys as the first 5 positive integers and values as their squares, and another with keys as the next 5 positive integers and values as their squares. Merge these dictionaries into a single dictionary and print it.

### Assignment 7: Nested Dictionaries

Create a nested dictionary representing a student with keys 'name', 'age', 'grades', where 'grades' is another dictionary with keys 'math', 'science', and 'english'. Print the nested dictionary.

### Assignment 8: Dictionary of Lists

Create a dictionary where the keys are the first 5 positive integers and the values are lists containing the first 5 multiples of the key. Print the dictionary.

### Assignment 9: Dictionary of Tuples

Create a dictionary where the keys are the first 5 positive integers and the values are tuples containing the key and its square. Print the dictionary.

### Assignment 10: Dictionary and List Conversion

Create a dictionary with the first 5 positive integers as keys and their squares as values. Convert the dictionary to a list of tuples and print it.

### Assignment 11: Dictionary Filtering

Create a dictionary with the first 10 positive integers as keys and their squares as values. Create a new dictionary containing only the key-value pairs where the key is even. Print the new dictionary.

### Assignment 12: Dictionary Key and Value Transformation

Create a dictionary with the first 5 positive integers as keys and their squares as values. Create a new dictionary with keys and values swapped. Print the new dictionary.

### Assignment 13: Default Dictionary

Create a default dictionary where each key has a default value of an empty list. Add some elements to the lists and print the dictionary.

### Assignment 14: Counting with Dictionaries

Write a function that takes a string and returns a dictionary with the count of each character in the string. Print the dictionary.

### Assignment 15: Dictionary and JSON

Create a dictionary representing a book with keys 'title', 'author', 'year', and 'genre'. Convert the dictionary to a JSON string and print it.

In [1]:
# Create a dictionary with the first 10 positive integers as keys and their squares as values. Print the dictionary.
d=dict()
for i in range(1,11):
  d[i]=i**2
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [3]:
# Print the value of the key 5 and the keys of the dictionary created in Assignment 1.
print("value of key 5 is :",d[5])
print("keys are : ",d.keys())

value of key 5 is : 25
keys are :  dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [4]:
# Add a new key-value pair (11, 121) to the dictionary created in Assignment 1 and then remove the key-value pair with key 1. Print the modified dictionary.
d[11]=121
d.pop(1)
print(d)

{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121}

In [6]:
# Iterate over the dictionary created in Assignment 1 and print each key-value pair.
for i,j in d.items():
  print("key : ",i,"value:",j)

key :  2 value: 4
key :  3 value: 9
key :  4 value: 16
key :  5 value: 25
key :  6 value: 36
key :  7 value: 49
key :  8 value: 64
key :  9 value: 81
key :  10 value: 100
key :  11 value: 121

In [7]:
# Create a new dictionary containing the cubes of the first 10 positive integers using a dictionary comprehension. Print the new dictionary.
d1={x:x**3 for x in range(1,11)}
print(d1)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}

In [13]:
# Create two dictionaries: one with keys as the first 5 positive integers and values as their squares, and another with keys as the next 5 positive integers and values as their squares. Merge these dictionaries into a single dictionary and print it.

d1={x:x**2 for x in range(1,5)}
d2={x:x**2 for x in range(6,11)}
d1.update(d2)
print(d1)

{1: 1, 2: 4, 3: 9, 4: 16, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [15]:
# Create a nested dictionary representing a student with keys 'name', 'age', 'grades', where 'grades' is another dictionary with keys 'math', 'science', and 'english'. Print the nested dictionary.

student = {
    'name': 'Alice',
    'age': 10,
    'grades': {
        'math': 90,
        'science': 85,
        'english': 92
    }
}

print(student['grades'])

{'math': 90, 'science': 85, 'english': 92}

In [17]:
# Create a dictionary where the keys are the first 5 positive integers and the values are lists containing the first 5 multiples of the key. Print the dictionary.
d={x:[x*i for i in range(1,6)]  for x in range(1,6)}
print(d)

{1: [1, 2, 3, 4, 5], 2: [2, 4, 6, 8, 10], 3: [3, 6, 9, 12, 15], 4: [4, 8, 12, 16, 20], 5: [5, 10, 15, 20, 25]}

In [20]:
# Create a dictionary where the keys are the first 5 positive integers and the values are tuples containing the key and its square. Print the dictionary.
d={x:(x,x**2) for x in range(1,6)}
print(d)

{1: (1, 1), 2: (2, 4), 3: (3, 9), 4: (4, 16), 5: (5, 25)}

In [23]:
# Create a dictionary with the first 5 positive integers as keys and their squares as values. Convert the dictionary to a list of tuples and print it.
d={x:x**2 for x in range(1,6)}
l=[]
for i,j in d.items():
  l.append((i,j))
print(l)

[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [30]:
# Create a dictionary with the first 10 positive integers as keys and their squares as values. Create a new dictionary containing only the key-value pairs where the key is even. Print the new dictionary.
d={x:x**2 for x in range(1,11)}
d1={k:v for k,v in d.items() if k%2==0}
print(d1)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100}

In [31]:
# Create a dictionary with the first 5 positive integers as keys and their squares as values. Create a new dictionary with keys and values swapped. Print the new dictionary.

d={x:x**2 for x in range(1,6)}
d1={v:k for k,v in d.items()}
print(d1)

{1: 1, 4: 2, 9: 3, 16: 4, 25: 5}

In [32]:
from collections import defaultdict
# Create a default dictionary where each key has a default value of an empty list. Add some elements to the lists and print the dictionary.
d=defaultdict(list)
d[1].append(2)
d[1].append(3)
d[2].append(4)

print(d)

defaultdict(<class 'list'>, {1: [2, 3], 2: [4]})

In [34]:
# Write a function that takes a string and returns a dictionary with the count of each character in the string. Print the dictionary.
def count(s):
  d=dict()
  s1=set(s)
  for i in s1:
    d[i]=s.count(i)
  return d
s="mahendra kandimalla"
print(count(s))

{'h': 1, 'n': 2, 'a': 5, 'k': 1, 'm': 2, 'd': 2, ' ': 1, 'i': 1, 'r': 1, 'l': 2, 'e': 1}

In [35]:
# Create a dictionary representing a book with keys 'title', 'author', 'year', and 'genre'. Convert the dictionary to a JSON string and print it.

import json

book_details = {
    'title': 'The Hitchhiker\'s Guide to the Galaxy',
    'author': 'Douglas Adams',
    'year': 1979,
    'genre': 'Science Fiction'
}

book_json = json.dumps(book_details, indent=4)

print(book_json)

{
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "year": 1979,
    "genre": "Science Fiction"
}